name: astrocore
main: dev.astroolean.Plugin
version: 1.0
api-version: 1.20
authors: [ Astroolean ]
description: My first plugin ever...
website: astroolean.dev
commands:
  hello:
    description: Says hello to the player.
    usage: /hello