name: AstroCore
main: dev.astroolean.Plugin
version: 1.0
api-version: 1.20
authors: [ Astroolean ]
description: My first plugin ever...
website: astroolean.dev
commands:
  astrocore:
    description: Enable or disable the AstroCore plugin
  hello:
    description: A friendly Hello command
