name: AstroCore
main: dev.astroolean.AstroCore
version: 1.4
api-version: 1.20
authors: [ Astroolean ]
description: My first plugin ever...
website: astroolean.dev
depend: []
commands:
  astrocore:
    description: "Enable or disable the AstroCore plugin..."
    usage: "/astrocore"
  hello:
    description: "A friendly Hello command..."
    usage: "/hello"
  help:
    description: "An anti-help command..."
    usage: "/help"
  snort:
    description: "Consume cocaine to gain effects..."
    usage: "/snort"
  smoke:
    description: "Consume weed to gain effects..."
    usage: "/smoke"
  gm:
    description: "Open the game mode selection GUI"
    usage: "/gm"
  t:
    description: "Open the time selection GUI"
    usage: "/t"
  w:
    description: "Open the weather selection GUI"
    usage: "/w"
  cc:
    description: "Clears the fucking chat..."
    usage: "/cc"
  god:
    description: "Gives absolute godmode..."
    usage: "/god"
  ac:
    description: "Provides basic information about the plugin..."
    usage: "/ac"
  rename:
    description: "Rename the item you are holding."
    usage: "/rename <name>"
  lore:
    description: "Set lore for the item you are holding."
    usage: "/lore <line> <text>"
  p:
    description: "Shows the list of installed plugins if you are OP."
    usage: "/p"
  pv:
    description: "PlayerVault storage for players..."
    usage: "/pv [number]"
  fix:
    description: "Repair your fucking items you lazy bum..."
    usage: "/fix [hand/all]"
  heal:
    description: "Heal yourself to full health."
    usage: "/heal"
  sethome:
    description: "Set a home location."
    usage: "/sethome [name]"
  home:
    description: "Teleport to a home location."
    usage: "/home [name]"
  delhome:
    description: "Delete a home location."
    usage: "/delhome [name]"
  homes:
    description: "View your current homes."
    usage: "/homes"
  feed:
    description: "Go ahead and feed yourself."
    usage: "/feed"
  spawn:
    description: "Set and go to the fucking spawn."
    usage: "/spawn [set]"

permissions:
  astrocore.use:
    description: Allows usage of the AstroCore commands.
    default: false
  astrocore.rename:
    description: Allows the player to rename items.
    default: false
  astrocore.lore:
    description: Allows the player to set item lore.
    default: false
  astrocore.plugins:
    description: Allows the player to see the list of installed plugins.
    default: op
  astrocore.pv:
    description: Allows the player to access the player vault.
    default: false
  astrocore.fix:
    description: Allows the player to repair items.
    default: false
  astrocore.heal:
    description: Allows the player to heal themselves.
    default: false
  astrocore.sethome:
    description: Allows the player to set home locations.
    default: false
  astrocore.home:
    description: Allows the player to teleport to home locations.
    default: false
  astrocore.delhome:
    description: Allows the player to delete home locations.
    default: false
  astrocore.homes:
    description: Allows the player to view their home locations.
    default: false
  astrocore.feed:
    description: Allows the player to feed themselves.
    default: false
  astrocore.spawn:
    description: Allows the player to set and teleport to spawn.
    default: false
  astrocore.clearChat:
    description: Allows the player to clear the chat.
    default: false
  astrocore.god:
    description: Allows the player to use god mode.
    default: false
  astrocore.smoke:
    description: Allows the player to get high.
    default: false
  astrocore.snort:
    description: Allows the player to get high.
    default: false
  astrocore.astrocore:
    description: Enable/disable the plugin.
    default: op
  astrocore.hello:
    description: Friendly hello message to the player.
    default: false
  astrocore.help:
    description: Directs you to the suicide hotline.
    default: false
